### ISSUE TITLE
Few episodes in arguments

### ISSUE THREAD

**Issue by captaincolonelfox** [POMATu/anime-tool#12]
What if I want to play next episode after watching first one or even something in the middle.
It may look like
`anime-tool ... -e 01,02,04`

I also can imagine something like range
`anime-tool ... -e 01-04`

Or even `ALL` may be an option
`anime-tool ... -e ALL`

Moreover, it may be, that I want to play, until I stop it. Something like that:
`anime-tool ... 05-*`

**Comment by POMATu** [comment]
How you gonna track that you stopped it (in the last case)?

**Comment by captaincolonelfox** [comment]
@POMATu 
Actually, you can stop at any episode so I wrote basic algorithm in #3:
Its save state (episode and variables) every time before it starts new episode.

So when I run: `04-*`:
Its starts on `04` and immediately write it to the file. If I exit on this episode it will open `04` episode next time when I run `anime-tool --continue`
But if code proceed to the `05` episode after watching `04` then, before opening `mpv` it rewrite variables in the file. And on the next run of `anime-tool --continue` it will open `05`

But the problem here is: how to understand the reason `mpv` closed. Maybe it returns code depends on who close it. Because on user interruption we need to exit script as well.

**Comment by POMATu** [comment]
issue related to obsolete version
