### ISSUE TITLE
Make movie folder argument optional

### ISSUE THREAD

**Issue by captaincolonelfox** [POMATu/anime-tool#6]
Usually, I just move to the folder with anime and then use `anime-tool`
So, basically, I will always use `./` as movie folder.

Maybe, we can make it `./` by default and if first passed argument is not a number of episode (type of int) then use passed path

**Comment by POMATu** [comment]
Yeah so with getargs library we have just two args to mess around, not 4 anymore. I am also using like that
* open folder with nautilus
* right click "Open terminal here"
* type anime-tool

But we should leave option to specify movie path, cause for example while watching Evangelion there was also a folder with "Directors cut" series, and I had to specify that folder to watch 21-24 episodes.  Because of such messes there is no option to grab all filetree with find and process that either.

I think the best option maybe to include that movie folder to getargs? So it gonna be optional
```
anime-tool 01 -m . -s ./subs -a ./audio
anime-tool 01 -s ./subs -a ./audio
```
And if it's not defined then current directory is taken: './'
It's gonna to be even more clean this way.

Please always pull before you do any changes.

**Comment by captaincolonelfox** [comment]
@POMATu 
Ok, and what if we move episode to `-e` option?
So then we can start first finded episode by default?

Btw, how can I change label or assign issue? Or only owner can do that? So, maybe, you can assign this one to me?

**Comment by POMATu** [comment]
added you as collaborator for this project, I think it should work after that.

We can move that to getargs too. As far as I remember array is sorted, but it needs some code to get first key from hash, cause first episode can be actually not 01 but 05. It can be 001 either

Something like that (not perl)
```
foreach (array as key => value) {
$firstkey = key;
break;
}
```
Maybe perl have subroutine for that stuff, it tends to have shot-hand solutions for everything.

So getting first episode automatically can be useful with this issue https://github.com/POMATu/anime-tool/issues/3
But I am not sure how to implement that issue that without ARGV[0]

**Comment by POMATu** [comment]
I think better sort hash by keys for sure before finding first episode
```
return %hashed_episodes;
```
^^^ here

**Comment by captaincolonelfox** [comment]
@POMATu 
Yep, sure.
I mean, you sort it anyways, right? In the end you print sorted hash so its not a problem, I guess.

What's the problem with ARGV[0] and continue watching from episode?

**Comment by POMATu** [comment]
hash is not sorted. I wonder if it can be sorted at all, cause it's not array
```
$VAR1 = '10';
$VAR2 = '[Zurako]_Dantalian_no_Shoka_10_(BD_720p_AAC)_[31DB05D4].ass';
$VAR3 = '03';
$VAR4 = '[Zurako]_Dantalian_no_Shoka_03_(BD_720p_AAC)_[14B23FD7].ass';
$VAR5 = '02';
$VAR6 = '[Zurako]_Dantalian_no_Shoka_02_(BD_720p_AAC)_[382AEE80].ass';
$VAR7 = '07';
$VAR8 = '[Zurako]_Dantalian_no_Shoka_07_(BD_720p_AAC)_[6DE45D1C].ass';
$VAR9 = '12';
$VAR10 = '[Zurako]_Dantalian_no_Shoka_12_(BD_720p_AAC)_[8981728F].ass';
$VAR11 = '08';
$VAR12 = '[Zurako]_Dantalian_no_Shoka_08_(BD_720p_AAC)_[EBA836CC].ass';
$VAR13 = '06';
$VAR14 = '[Zurako]_Dantalian_no_Shoka_06_(BD_720p_AAC)_[01AC9B57].ass';
$VAR15 = '09';
$VAR16 = '[Zurako]_Dantalian_no_Shoka_09_(BD_720p_AAC)_[4ED50F37].ass';
$VAR17 = '11';
$VAR18 = '[Zurako]_Dantalian_no_Shoka_11_(BD_720p_AAC)_[FC0B2E19].ass';
$VAR19 = '05';
$VAR20 = '[Zurako]_Dantalian_no_Shoka_05_(BD_720p_AAC)_[54F8BE5B].ass';
$VAR21 = '04';
$VAR22 = '[Zurako]_Dantalian_no_Shoka_04_(BD_720p_AAC)_[444EED7E].ass';
$VAR23 = '01';
```
gonna fix now

so for issue #3 that options: next,previous and last needs to fit somehow current arguments model. Better think about that now, maybe you can propose something?

My idea:
* App saves all arguments to text file in profile folder every execution including even working directory variable
* After that if app sees instead of usual arguments "next" argument - then it reads that file, increments episode number, writes all that vars to ARGV and executes as usual

Also better not to increment +1 but to take next available episode from hash keys

**Comment by POMATu** [comment]
so this stuff didn't work, will have more time to mess with that later
```
sub get_first_episode {
	foreach my $num (sort keys %_) {
		return $num;
	}
}
```
This may help 
https://perlmaven.com/how-to-sort-a-hash-in-perl

And conversion to array is not acceptable cause keys with preceeding zeroes will be lost then

I think you can just think about how to organize args more clean way including for issue #3 and I'll do that bullshitting with hash sorting later.

**Comment by captaincolonelfox** [comment]
@POMATu 
```
my %anime = (
	'09' => 'Wangan Midnight - 04 [DVDRip 1280x720 x264 AC3]',
	'08' => 'Wangan Midnight - 04 [DVDRip 1280x720 x264 AC3]',
	'06' => 'Wangan Midnight - 04 [DVDRip 1280x720 x264 AC3]',
	'07' => 'Wangan Midnight - 04 [DVDRip 1280x720 x264 AC3]',
	'11' => 'Wangan Midnight - 04 [DVDRip 1280x720 x264 AC3]',
	'10' => 'Wangan Midnight - 04 [DVDRip 1280x720 x264 AC3]'
);

foreach my $episode (sort keys %anime) {
	print "$episode\n";
};
```
This code gives me following output:
```
06
07
08
09
10
11
```

Isn't that we are looking for?

**Comment by captaincolonelfox** [comment]
@POMATu 
Accidentally close issue, oopsie :p

Ok, I will take a look on it.  Will work on agruments and options.
Will post to #3 if find any solution with sorting

**Comment by POMATu** [comment]
Done. This functions gets any episode number from hash that you can need ever
```
sub get_episode_key {
	my $step = shift;
	my $base_ep = shift;
    my %hash = %{$_[0]};
    
    my $counter = 0;
    my $max_counter = abs $step;

    if ($base_ep == -1) {
    	foreach my $num (sort keys %hash) {
    		return $num;
    	}
    }

    if ($step>=0) {
		foreach my $num (sort keys %hash) {

			if ($counter > 0) {
				$counter++;
			}
			if ($num == $base_ep) {
				$counter++;
			}
			if ($counter>$max_counter) {
				return $num;
			}
		}
	} else {
		foreach my $num (reverse sort keys %hash) {

			if ($counter > 0) {
				$counter++;
			}
			if ($num == $base_ep) {
				$counter++;
			}
			if ($counter>$max_counter) {
				return $num;
			}
		}
	}
}
```
Arguments:
$step,$base_ep,ref to %hash
Example:
Getting next episode from 5th episode:
```get_episode_key(1,5,\%hashed_movies);```
06

Getting previous episode from 5th episode
```get_episode_key(-1,5,\%hashed_movies);```
04

Getting 5th episode key
```get_episode_key(0,5,\%hashed_movies);```
05

Getting next +2 episode from 5th episode
```get_episode_key(+2,5,\%hashed_movies);```
07

Get first episode:
```get_episode_key(-1,-1,\%hashed_movies);```
01

When base episode is incorrect or when there is no next/prev episode - nothing returned. So it should cover all cases I guess

You can use that or I will use that later

**Comment by POMATu** [comment]
```
sub get_episode_key {
	my $step = shift;
	my $base_ep = shift;
    my %hash = %{$_[0]};
    
    my $counter = 0;
    my $max_counter = abs $step;

    if ($base_ep == -1) {
    	foreach my $num (sort keys %hash) {
    		return $num;
    	}
    }

    if ($step>=0) {
		foreach my $num (sort keys %hash) {

			if ($counter > 0) {
				$counter++;
			}
			if ($num eq $base_ep) {
				$counter++;
			}
			if ($counter>$max_counter) {
				return $num;
			}
		}
	} else {
		foreach my $num (reverse sort keys %hash) {

			if ($counter > 0) {
				$counter++;
			}
			if ($num eq $base_ep) {
				$counter++;
			}
			if ($counter>$max_counter) {
				return $num;
			}
		}
	}
}
```
That will be more correct, to compare strings instead of ints

Get first episode:
 get_episode_key(-1,-1,\%hashed_movies);

Getting previous episode from 5th episode
get_episode_key(-1,"05",\%hashed_movies);
04

**Comment by captaincolonelfox** [comment]
@POMATu 
Nice, good work here.
Maybe you need to commit it? Then I can pull it and merge with my branch.

Anyways, I think I will leave it to you. And I for now will just stick with the arguments structure.

**Comment by POMATu** [comment]
sure, done

**Comment by captaincolonelfox** [comment]
@POMATu 
Are we still using episodes as argument? Or we move it to options too?

We can implement both: e.g look for argument if its not passed as an options,
And if argument is empty too then start with the first episode.

**Comment by POMATu** [comment]
Yeah I guess that's not important, you can do how you like.
